// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "imgui_impl_win32.h"

#include <stdio.h>

#include <windows.h>

extern
IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);

// Wrap this in a namespace to keep it separate from the C++ API
namespace cimgui
{
#include "cimgui_impl_win32.h"
}

// By-value struct conversions

// Function stubs

#ifndef IMGUI_DISABLE

CIMGUI_API bool cimgui::cImGui_ImplWin32_Init(void* hwnd)
{
    return ImGui_ImplWin32_Init(hwnd);
}

CIMGUI_API bool cimgui::cImGui_ImplWin32_InitForOpenGL(void* hwnd)
{
    return ImGui_ImplWin32_InitForOpenGL(hwnd);
}

CIMGUI_API void cimgui::cImGui_ImplWin32_Shutdown(void)
{
    ImGui_ImplWin32_Shutdown();
}

CIMGUI_API void cimgui::cImGui_ImplWin32_NewFrame(void)
{
    ImGui_ImplWin32_NewFrame();
}

CIMGUI_API LRESULT cimgui::cImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
    return ImGui_ImplWin32_WndProcHandler(hWnd, msg, wParam, lParam);
}

CIMGUI_API void  cimgui::cImGui_ImplWin32_EnableDpiAwareness(void)
{
    ImGui_ImplWin32_EnableDpiAwareness();
}

CIMGUI_API float cimgui::cImGui_ImplWin32_GetDpiScaleForHwnd(void* hwnd)
{
    return ImGui_ImplWin32_GetDpiScaleForHwnd(hwnd);
}

CIMGUI_API float cimgui::cImGui_ImplWin32_GetDpiScaleForMonitor(void* monitor)
{
    return ImGui_ImplWin32_GetDpiScaleForMonitor(monitor);
}

CIMGUI_API void cimgui::cImGui_ImplWin32_EnableAlphaCompositing(void* hwnd)
{
    ImGui_ImplWin32_EnableAlphaCompositing(hwnd);
}

#endif // #ifndef IMGUI_DISABLE
