name: build

on:
  push:
  pull_request:
  workflow_run:
    # Use a workflow as a trigger of scheduled builds. Forked repositories can disable scheduled builds by disabling
    # "scheduled" workflow, while maintaining ability to perform local CI builds.
    workflows:
      - scheduled
    types:
      - requested

jobs:
  Linux:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - docking
        compiler:
          - gcc
          - clang

    steps:
    # Checkout both repositories
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        path: imgui
        repository: ocornut/imgui
        ref: ${{ matrix.branch }}
        fetch-depth: 1

    - name: Dependencies
      run: |
        sudo pip3 install ply

    - name: Generate
      run: |
         python3 dear_bindings.py --output cimgui          imgui/imgui.h
         # imgui_internal.h disabled for now as it generates errors
         # python3 dear_bindings.py --output cimgui_internal imgui/imgui_internal.h

    - name: Build
      run: |
        # FIXME: cimgui_internal.cpp can be added when generator produces compilable result.
        ${{ matrix.compiler }}                  \
          -o example_null                       \
          -Iimgui -I.                           \
          -x c examples/example_null.c          \
          -x c++ cimgui.cpp                     \
          imgui/imgui.cpp                       \
          imgui/imgui_demo.cpp                  \
          imgui/imgui_draw.cpp                  \
          imgui/imgui_tables.cpp                \
          imgui/imgui_widgets.cpp               \
          -lm -lstdc++

    - name: Run
      run: ./example_null

    - uses: actions/upload-artifact@v3
      with:
        name: dear_bindings_${{ matrix.branch }}
        path: |
          cimgui.*
          cimgui_internal.*
